version: '3'

services:

  api:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    command: uvicorn "main:app" --host=0.0.0.0 --port=${API_PORT} --log-level="info"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

  worker:
    build: .
    command: /bin/sh -c 'python worker.py'
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

  rabbitmq:
    image: rabbitmq:3.13.1-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
      interval: 60s
      timeout: 15s
      retries: 3
    restart: always